### ISSUE TITLE
Multidatastreams

### ISSUE THREAD

**Issue by prac05** [FraunhoferIOSB/frost-sensorthings-datasource#445]
Hi,

I'm trying to display the results of a MultiDatastream, but I'm not getting any results. Does this plugin have this feature?

![sensorthings](https://github.com/user-attachments/assets/d38a44bd-3a16-4a54-bdfd-95daadf444a4)

**Comment by claudiadragoste** [comment]
Hello, I was having the same doubt; before opening a new issue, checking if somebody has the same problem, I found this issue. Is it possible to show the observations for a Multidatastream? If not, I would like to know who I should talk with for developing it. Thank you

**Comment by hylkevds** [comment]
Does it work if you put in:
```
$.value[*].result[0]
```
?

**Comment by claudiadragoste** [comment]
Thank you, Hylke!
